### PR TITLE
Add misaligned c.jalr and c.jr instruction test

### PR DESCRIPTION
**Pull request by rogerchang23424**
## Description

This PR added the additional test case for c.jalr and c.jr with the misaligned address in the register to verify the implementation.

### Related Issues

NA

### Ratified/Unratified Extensions

- [x] Ratified
- [ ] Unratified

### List Extensions

> List the extensions that your PR affects. In case of unratified extensions, please provide a link to the spec draft that was referred to make this PR.

### Reference Model Used

- [X] SAIL
- [X] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [ ] All tests are compliant with the test-format spec present in this repo ?
  - [X] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [X] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [ ] Link to Google-Drive folder containing the new coverage reports ([See this](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/CONTRIBUTION.md#uploading-test-stats) for more info): < SPECIFY HERE >
  - [ ] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE > 
  - [ ] Changelog entry created with a minor patch

### Optional Checklist:

  - [X] RISCV-V CTG PR link if tests were generated using it : https://github.com/riscv-software-src/riscv-ctg/pull/116
  - [X] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

### CODE REVIEW

**Comment by allenjbaum** [comment]
Please change this to be a PR to the dev branch

**Comment by rogerchang23424** [comment]
> Please change this to be a PR to the dev branch

Done. Please check.

**Comment by UmerShahidengr** [comment]
Good work @rogerchang23424 , but we need the coverpoint definitions for these tests, otherwise riscof coverage command will not work on these tests.

**Comment by rogerchang23424** [comment]
Hi, I have added the `misalign1-cjalr` and `misalign1-cjr` coverage in the separated PR. Sorry for waiting for a long time to update it.

**Review by jamesbeyond — APPROVED** [review]
LGTM

**Pull request merged**
