### PR TITLE
Add a CI script to update the `encoding.h` file

### PR DESCRIPTION
**Pull request by Abdulwadoodd**
As discussed in the issue [here](https://github.com/riscv-non-isa/riscv-arch-test/issues/263), the latest version of `encoding.h` file can be generated from [riscv/riscv-opcodes](https://github.com/riscv/riscv-opcodes) repository by running `make`. So, instead of maintaining a separate copy of `encoding.h` in this repository, we mush by pulling the latest version of this file from the parent [riscv/riscv-opcodes](https://github.com/riscv/riscv-opcodes) repository. 
So, I have written a CI script that does the same. On every `push` or `pull_request`, CI will invoke and replaces the old encoding with the latest one.

### CODE REVIEW

**Comment by pawks** [comment]
Looks like the CI is failing. It might require some additional changes. Note that the main branch is protected and direct pushes to main are disalowed.

**Comment by Abdulwadoodd** [comment]
I've changed the script so that it would trigger on the pull request, should that work fine? Also, what is the alternative to direct pushes to the main branch if it is disallowed

**Comment by pawks** [comment]
Only Merge/pull requests are allowed to master.

**Comment by neelgala** [comment]
I am not completely comfortable with this automated check-in of files. The encoding.h here should be updated when the tests in this repo require those updates in encoding.h. This will make sure that the modifications in encoding.h are in sync with changes in tests. 

Also, the encoding.h generated in riscv-opcodes is specifically designed to be consumed by spike (certain pseudo-ops are ommitted) and the changes that happen there will be specific to that. Automated check-ins have the potential of pulling in something that is non-backward compatible and break things here - which shouldn't be the case.

Solution should be to manually check-in encoding.h as an when required.

**Comment by allenjbaum** [comment]
I'm not sure if you're uncomfortable with the  concept of automated
check-in, or the conditions under which it is checked in.
E.g. is limiting it to when merges  are approved implementable, and if so -
why would that make you uncomfortable?

I'm more concerned with how to ensure that the right toolchain(s) get used,
which seems to be a more overriding problem,
but that is out of our hands.

**Comment by neelgala** [comment]
having an untested code-check in is what is scary. Right now all merges are manually verified (by contributors and owners of this repo). Having a CI to commit a code without due testing = recipe for chaos. Having the CI test before committing has the  issue of which toolchain should be used for that test - because unratified tests will probably work with custom toolchains which are not upstream yet. If a PR warrants a change in the encoding.h then it should be done as part of that PR. Steps to generate the encoding.h from riscv-opcodes can be captured in the docs somewhere.

**Pull request closed without merging**
