### PR TITLE
Update encoding.h

### PR DESCRIPTION
**Pull request by dansmathers**
<FOR DOC UPDATES FILL ONLY DESCRIPTION AND RELATED ISSUES SECTION AND REMOVE THE OTHERS>

## Description

> Provide a detailed description of the changes performed by the PR.
Adding CLIC (fast-interrupt) new CSR defines for m-mode and s-mode.  Ran SAIL regression.  Adding new unreferenced defines are a pretty safe change but I verified nothing broke.

### Related Issues

> Please list all the issues related to this PR. Use NA if no issues exist

### Ratified/Unratified Extensions

- [ ] Ratified
- [X] Unratified

### List Extensions

> List the extensions that your PR affects. In case of unratified extensions, please provide a link to the spec draft that was referred to make this PR.
smclic, ssclic
### Reference Model Used

- [X] SAIL
- [ ] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [ N/A] All tests are compliant with the test-format spec present in this repo ?
  - [ N/A] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [ N/A] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [ N/A] Link to Google-Drive folder containing the new coverage reports ([See this](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/CONTRIBUTION.md#uploading-test-stats) for more info): < SPECIFY HERE >
  - [ N/A] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE > 
  - [ ] Changelog entry created with a minor patch

### Optional Checklist:

  - [ ] RISCV-V CTG PR link if tests were generated using it : < SPECIFY HERE >
  - [ ] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

### CODE REVIEW

**Comment by dansmathers** [comment]
This is my first attempt at a riscv-arch-test pull and I'm a bit new using riscv-arch-test. can you check I added the new CSR definitions correctly?

**Review by allenjbaum — APPROVED** [review]
Looks good to me

**Comment by dansmathers** [comment]
I found this:
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/encoding.h was  auto-generated by running 'make' in  https://github.com/riscv/riscv-opcodes (5adef50)

and it looks like the clic CSRs are already included in https://github.com/riscv/riscv-opcodes/blob/master/constants.py and in https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/encoding.h

maybe this riscv-arch-test encoding.h is just out of date and needs to be updated?

**Comment by allenjbaum** [comment]
We have decided  update of encoding.h should wait until you actually have tests to submit. This won't be merged until you have tests to merge.

**Pull request closed without merging**
