### PR TITLE
Cleaning fflags csr after each test

### PR DESCRIPTION
**Pull request by misterjdrg**
Replace `csrrs flagreg, fflags, x0` -> `csrrw flagreg, fflags, x0`, so fflags part of fcsr set to 0 after each test.

### CODE REVIEW

**Review by allenjbaum — APPROVED** [review]
This reads and clears the FCSR after each test which is necessary to enable testing for the correct settings of the summary status. Note that this will require that reference signature will need to be updated for every test in the current framework, but will not be required for the riscof framework. Also note that we still need to add  the infrastructure to measure the CSR side-effects, the coverpoints that test them, and possibly new tests to exercise the coverpoints.

**Comment by misterjdrg** [comment]
I tested all extensions for rv32i_m and rv64i_m, except K (gcc throws `Error: unrecognized opcode `aes64ds x12,x10,x11'`)

**Comment by pawks** [comment]
@misterjdrg Please update `CHANGELOG.md` with an entry for this.

**Comment by misterjdrg** [comment]
@pawks Done

**Pull request merged**
