### PR TITLE
[ACT]fix fcvt_d_s testcases

### PR DESCRIPTION
**Pull request by Pagerd**
### Description
change fcvt.d.s NaN-boxed input
### Related Issues
https://github.com/riscv-non-isa/riscv-arch-test/issues/559

### Ratified/Unratified Extensions
- [X] D

### Reference Model Used
- [X] SAIL

### Mandatory Checklist:
- [x] All tests are compliant with the test-format spec present in this repo ?
- [X] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
- [X] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
- [X] Link to Google-Drive folder containing the new coverage reports): < [coverage reports ](https://drive.google.com/drive/folders/1BO2CSCInwqirH70-gprP9pkdnjWXuvRj) >

### CODE REVIEW

**Review by allenjbaum — COMMENTED** [review]
I'd much rather see this data in hex rather than decimal. I have no confidence in what it is doing by looking at this.

**Comment by Pagerd** [comment]
> I'd much rather see this data in hex rather than decimal. I have no confidence in what it is doing by looking at this.

All D extension test cases are tested using decimal data, including the modified `fcvt.d.s` test case, so I used the same method to modify it. Is there a problem with this method? Many test cases are tested in this way

**Comment by allenjbaum** [comment]
IEEE FP is a binary format, not a decimal format.
So yes, there is a problem for anyone who reviews the tests  (me).
And, yes, that should have been followed for the earlier tests as well.

**Comment by UmerShahidengr** [comment]
This one is a simple fix, we can merge this one, and start an effort to convert all NAN_BOXED data in hex rather than decimal. I will create an issue on this.

**Review by UmerShahidengr — APPROVED** [review]
Looks good to go

**Pull request merged**
