### PR TITLE
Misaligned support

### PR DESCRIPTION
**Pull request by Mudassir10X**
## Description

I wrote these tests to analyze the misaligned load/store support in RISC-V along with the high priority misalign exception and low addr first flags in Sail-riscv. I followed the folowing [Test-plan](https://docs.google.com/spreadsheets/d/1Uq9FaWlvhGjLBqIaG0kg0q6vtY_k6pi_i7Qt-fXnwPI/edit?usp=sharing). These tests include the following conditions:
- PMP regions Boundary
- Shared PMP Region
- PTE Boundary
- PMP-misalign exception priority
- PTE-PMP-misalign combined exception priority

My Action-plan for these 3 flags and the result were as follows:
image

### Related Issues

> Please list all the issues related to this PR. Use NA if no issues exist

### Ratified/Unratified Extensions

- [x] Ratified
- [ ] Unratified

### List Extensions

> List the extensions that your PR affects. In case of unratified extensions, please provide a link to the spec draft that was referred to make this PR.

### Reference Model Used

- [x] SAIL
- [ ] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [x] All tests are compliant with the test-format spec present in this repo ?
  - [x] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [ ] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [ ] Link to Google-Drive folder containing the new coverage reports ([See this](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/CONTRIBUTION.md#uploading-test-stats) for more info): < SPECIFY HERE >
  - [ ] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE > 
  - [ ] Changelog entry created with a minor patch

### Optional Checklist:

  - [ ] RISCV-V CTG PR link if tests were generated using it : < SPECIFY HERE >
  - [ ] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

### CODE REVIEW

**Review by allenjbaum — COMMENTED** [review]
Do you have more information about exactly what failed?
Note that many of the optionos needed for this test (e.g. whether the high or low address is executed first) must be configured into the models (the reference model, and the DUT), which are generally SAIL and SPIKE, neither of which have any way of configuring those options.
For misaligned access, I think that each model has to be compiled. to have that support or not, as well.

Can you please indicate what exactly failed for each of the failures?

**Comment by Mudassir10X** [comment]
Yes, the Sail model. Have different flags for each option. Which were tested individually by changing the sail configuration file made by Riscof.
I analyzed only sail for my tests and analysis with all flags was logged into the [Sail-analysis](https://docs.google.com/document/d/18HjZIPJkdUrNfKUvzLsN5umGGPqq2qvL_b6l_KohJ0w/edit?usp=drivesdk) file that you can review.
Moreover, cover points are being written for the coverage of these tests.

**Comment by allenjbaum** [comment]
I thought I had replied to this. You have different flags for each option,
but I was unaware that SAIL supported hi/low access ordering for
misaligned, or that it supported misalign exceptions being higher or lower
priority. I think you said you had a fork of Sail that supported these, but
if you do and you got incorrect results (based on hand inspection or
hand-written expected results) then doesn't that mean your fork has bugs?
I am missing something here, but I'm otherwise encouraged that you have
been able to test this.

**Comment by allenjbaum** [comment]
ah, OK

**Comment by Mudassir10X** [comment]
This PR will be shifted to another with clean commit history.

**Pull request closed without merging**
