### PR TITLE
Clean up

### LINKED ISSUE #262: Possible bug in priviledge/missaligned load tests
Hi, 

I'm having some issue with the rv64i_m/privilege/misalign_l* tests, all others test are passing fine.

From what I've seen, on a trap (misaligned  load or store), the common_mexcpt_handler save the offset between mtval and mtrap_sigptr (inside the RVMODEL_DATA section) into the trap signature area.

```
    	
   adj_mtval:
          csrr   t2, CSR_MCAUSE  /* code begin adjustment amount already in t3 */
  
          LI(t4, CODE_REL_TVAL_MSK)   /* trap#s 12, 3,1,0, -- adjust w/ code_begin */
          sll     t4, t4, t2		          /* put bit# in MSB */
          bltz    t4, sv_mtval		        /* correct adjustment is code_begin in t3 */
  
          LA(     t3, mtrap_sigptr) /* adjustment assuming access is to signature region */ 

```

It works well for the Store misaligned but the TEST_LOAD macro use the symbol rvtest_data as a base address for load, which is inside the RVTEST_DATA section, not the RVMODEL_DATA. This could lead in some issue if we do not use the default sections address. 

```
RVTEST_DATA_BEGIN
.align 4
rvtest_data:
.word 0xbabecafe
RVTEST_DATA_END

RVMODEL_DATA_BEGIN
....
....
#ifdef rvtest_mtrap_routine

mtrap_sigptr:
    .fill 64*(XLEN/32),4,0xdeadbeef

#endif
....
....
RVMODEL_DATA_END
```

Is there any reason to have a base adress set to rvtest_data in TEST_LOAD whilst TEST_STORE use the swreg value?
```
#define TEST_STORE(swreg,testreg,index,rs1,rs2,rs2_val,imm_val,offset,inst,adj)   ;\
LI(rs2,rs2_val)                                                             ;\
addi rs1,swreg,offset+adj                                                     ;\
LI(testreg,imm_val)                                                         ;\
sub rs1,rs1,testreg                                                          ;\
inst rs2, imm_val(rs1)                                                      ;\
nop                                                                         ;\
nop                                                                         

#define TEST_LOAD(swreg,testreg,index,rs1,destreg,imm_val,offset,inst,adj)   ;\
LA(rs1,rvtest_data+(index*4)+adj-imm_val)                                      ;\
inst destreg, imm_val(rs1)                                                   ;\
nop                                                                         ;\
nop                                                                         ;\
RVTEST_SIGUPD(swreg,destreg,offset) 

```

For some PMA/cacheability and testbench reasons, I have to move the signature section at 0x30000000.

### PR DESCRIPTION
**Pull request by pawks**
This PR has the following changes.
- Canaries (labels - sig_begin_canary. tsig_begin_canary, tsig_end_canary, sig_end_canary)
- Signature boundary labels (rvtest_sig_begin and rvtest_sig_end) (enables the new trap handler to fix #262)
- Zicsr ISA update for priv tests (#233)
- Default data section should be 16 bytes. This expands default rvtest_data region to be at least 16 bytes (#211)
- Replace la/li ops with LA/LI macros in tests (#275)
- Remove trap handler enable macro from misalign1-jalr tests (#281)
- Move misalign1-jalr test into I directory. (#281)
- Move fmem tests into the [F|D]/src directory
- Fix correctval in tests to ?? instead of 0. (#256)
- Remove the riscv-target directory (#259)
- Fix the store instruction used in 64bit K tests from `sw` to `SREG` (#282)

I shall update the changelog once the PR is deemed ready to merge.

### CODE REVIEW

**Review by allenjbaum — CHANGES_REQUESTED** [review]
It looks like files in the target directory were deleted, but the subolders containing them were not, and neither was the target directory itself.

**Comment by pawks** [comment]
> It looks like files in the target directory were deleted, but the subolders containing them were not, and neither was the target directory itself.

I have deleted the files. You can verify this on the branch [here](https://github.com/riscv-non-isa/riscv-arch-test/tree/clean-up). The entire `riscv-target` directory has been deleted.

**Review by allenjbaum — APPROVED** [review]
OK, this is good to gp now

**Review by allenjbaum — APPROVED** [review]
This looksw like it is ready to merge - assuming it passes CI, etc.

**Pull request merged**
