### PR TITLE
Misc fixes

### LINKED ISSUE #214: Test Format Spec doesn't specify the order of line in the signature file
That should be clarified to be: 
  in the order it is stored in the signature region, from lowest address to highest (from  RVMODEL_DATA_BEGIN to RVMODEL_DATA_END)

### LINKED ISSUE #230: comments in reference_output
As we are writing custom tests by hand, it's challenging to keep track of the meaning of the values in the reference_output.  We decided to add comments delimited by # in the reference_output.  We modified one line of the verify.sh script to ignore these comments when running a diff against signature.output, and think this feature might be helpful to other people.

verify.sh
    diff --ignore-case --ignore-trailing-space --strip-trailing-cr <(grep -o '^[^#]*' ${ref}) ${sig} &> /dev/null

### PR DESCRIPTION
**Pull request by neelgala**
- modified verify.sh to ignore comments in reference signature during diff operation [close #230]
 - udpated test-format spec to include the order of lines in the signature file [close #214]
 - RVTEST_E macro to be enabled for all rv32E tests. [#227]
 - Added a disclaimer in README about migration to RISCOF

### CODE REVIEW

**Review by pawks — APPROVED** [review]

**Comment by neelgala** [comment]
@allenjbaum added disclaimer in this PR. Please let me know if any changes required.

**Review by allenjbaum — COMMENTED** [review]
Didn't we just add an option for outputting 64bits (16 character) per line?
I think that needs to be documented here, along with the flag that enables it.

**Comment by neelgala** [comment]
@allenjbaum no we don't have any such option/support where the signature can be 64bits per line.

**Comment by allenjbaum** [comment]
Um, it was just added to Sail by Bilal. See PR#136

**Comment by neelgala** [comment]
but how does that affect the current framework ? you want to host multiple references for each test ? For RISCOF I understand that will change the SAIL plugins and config options- but don't really see what should happen in the current framework/spec ?

**Comment by allenjbaum** [comment]
This was requested by Marc, who needed it for his environment. It's an
option someone can use, not a requirement. It shouldn't affect the current
framework, just an environment like Marc's.

**Comment by neelgala** [comment]
well.. then can we have Marc submit a PR for that ? Does the current PR have to be gated by that ?

**Comment by allenjbaum** [comment]
OK, I was confused. 
What he fixed was in sail-riscv, not in arch-test. Sorry for the confusion.
For some reason I thought that this was affected by his changes - but it isn't.

**Comment by bilalsakhawat-10xe** [comment]
Hi,
Does this mean I should change 
https://github.com/riscv-non-isa/riscv-arch-test/blob/307c77b26e070ae85ffea665ad9b642b40e33c86/riscv-test-suite/rv32e_unratified/E/src/add-01.S#L31
and remove `def RVTEST_E = True;` from every rv32e test (change riscv-ctg) ? Because is unnecessary now.
Otherwise change for rv32e_unratified LGTM.
Thanks!

**Comment by pawks** [comment]
> Hi, Does this mean I should change
> 
> https://github.com/riscv-non-isa/riscv-arch-test/blob/307c77b26e070ae85ffea665ad9b642b40e33c86/riscv-test-suite/rv32e_unratified/E/src/add-01.S#L31
> 
> 
> and remove `def RVTEST_E = True;` from every rv32e test (change riscv-ctg) ? Because is unnecessary now.
> Otherwise change for rv32e_unratified LGTM.
> Thanks!

No, this is a temporary fix for the bash scripts based framework in this repo. To run the tests with riscof, that line in the tests is necessary.

**Review by bilalsakhawat-10xe — APPROVED** [review]

**Pull request merged**
