### PR TITLE
Add read-only CSR MCONFIGPTR test

### PR DESCRIPTION
**Pull request by dansmathers**
<FOR DOC UPDATES FILL ONLY DESCRIPTION AND RELATED ISSUES SECTION AND REMOVE THE OTHERS>

## Description

mconfigptr is a read-only CSR defined in priv spec 1.12.  The test attempts a read/write (illegal instruction exception expected)/read.  The read data value is implementation dependent so the read data value is ignored.

### Related Issues

Requires sail update for signatures to pass: https://github.com/riscv/sail-riscv/pull/293

### Ratified/Unratified Extensions

- [X ] Ratified
- [ ] Unratified

### List Extensions

MCONFIGPTR exists in the priv spec 1.12 and used by the discovery task group.

### Reference Model Used

- [X] SAIL
- [X] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [X] All tests are compliant with the test-format spec present in this repo ?
  - [X] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [ ] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [ ] Link to Google-Drive folder containing the new coverage reports ([See this](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/CONTRIBUTION.md#uploading-test-stats) for more info): < SPECIFY HERE >
  - [ ] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE > 
  - [ ] Changelog entry created with a minor patch

### Optional Checklist:

  - [ ] RISCV-V CTG PR link if tests were generated using it : < SPECIFY HERE >
  - [ ] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

### CODE REVIEW

**Review by allenjbaum — CHANGES_REQUESTED** [review]
This needs 2 nops after an op that might trap, because the trap handler always returns to the following double-word aligned instruction (deliberately, so we can write tests that do different things depending on whether a trap occurred or not, in addition to writing a trap signature

**Comment by allenjbaum** [comment]
This also needs a coverage definition, or this will fail when riscovof runs the coverage command

**Comment by UmerShahidengr** [comment]
This PR is on halt since last 3,4 months. @dansmathers please update the test and add coverpoint definitions so that it can be merged.

**Comment by jamesbeyond** [comment]
Sorry, removed the `CHANGELOG.MD` by mistake, need to be reverted

**Comment by UmerShahidengr** [comment]
This PR stayed halt for an year, there has been no updates on this one, and it requires major rebase. Closing this one out

**Pull request closed without merging**
