### PR TITLE
fix for LLVM compiler support

### PR DESCRIPTION
**Pull request by jsleroy**
Update arch_test.h code so that code compiles also with LLVM compilers.

`.if` changed to `.ifc` due to an issue in LLVM. This construct raise an "expected absolute expression" error. See similar issue reported in LLVM https://github.com/llvm/llvm-project/issues/53728

`.set` used to declare/update variables.

Modified code still run with GCC.

### CODE REVIEW

**Comment by neelgala** [comment]
Can you add an entry in the CHANGELOG so that I can merge it ?

**Comment by jsleroy** [comment]
Yes sure, will update the branch.

**Comment by jsleroy** [comment]
Updated CHANGELOG. Not sure about the version/date so feel free to correct them.

**Comment by neelgala** [comment]
I don't see the CHANGELOG update in this PR. You can create a 2.7.3 version entry

**Comment by jsleroy** [comment]
Sorry, fixed. I had put already 2.7.3, so we're fine here.

**Pull request merged**
