### PR TITLE
Ci fix

### PR DESCRIPTION
**Pull request by UmerShahidengr**
I have fixed the dependencies in CI.

### CODE REVIEW

**Comment by UmerShahidengr** [comment]
@jamesbeyond , @allenjbaum please review this one. This CI is passing all CI errors

**Review by jamesbeyond — APPROVED** [review]
LGTM

**Comment by jamesbeyond** [comment]
Seems CI still got some issues

**Comment by jamesbeyond** [comment]
@UmerShahidengr I think this error come from pip3, 
please checkout this post, seems there are some workarounds:
https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3

**Pull request merged**
