### PR TITLE
Resolved the bug in ISAC -> local variable 'yaml' referenced before assignment

### PR DESCRIPTION
**Pull request by UmerShahidengr**
PR #549 triggered an error in ISAC in util.py i.e, local variable 'yaml' referenced before assignment. I have given its fix

### CODE REVIEW

**Comment by UmerShahidengr** [comment]
@MuhammadHammad001 it is fixed now.
@allenjbaum can you please merge this one?

**Review by allenjbaum — APPROVED** [review]
simple update to newer version of yaml tool

**Comment by trdthg** [comment]
wait, looks like you redefined the `create_yaml`?

https://github.com/riscv-non-isa/riscv-arch-test/pull/549/files#diff-434f8fbdde31f9ea4a5f981af759b83518a41efe33f62a5050acddb0adb75c80R17-R27

**Comment by UmerShahidengr** [comment]
> wait, looks like you redefined the `create_yaml`?

Yes, I had to redefine it because without this function, ISAC was giving unreferenced error on `yaml` as it was getting defined in a if-condition only. The updated definition of `create_yaml()` is resolving that error.

**Pull request merged**
