### PR TITLE
Added tests for Floating point memory operations. 

### PR DESCRIPTION
**Pull request by pawks**
Added tests for aligned floating point load and store operations.

### CODE REVIEW

**Comment by allenjbaum** [comment]
This line 918 of arch_test.h should be split into 2 lines.
+918.  LI(testreg, fcsr_val); csrw fcsr, testreg                                                ;\
 It's technically correct, but a bit jarring

**Comment by neelgala** [comment]
@allenjbaum can I merge this ?

**Comment by allenjbaum** [comment]
yes, go ahead,

**Comment by allenjbaum** [comment]
This one is ready to go

**Review by allenjbaum — APPROVED** [review]
This should be good to go now. We do need to add comments to macros that explain how they are used, however, but that shouldn't hold up merging for now; that can be done when we merge in the split arch_test.h / test_macros.h file

**Pull request merged**
