### PR TITLE
Fix typos in CONTRIBUTION.md

### PR DESCRIPTION
**Pull request by visitorckw**
- the the RVI approved-> the RVI approved
- you are be expected to -> you are expected to

### CODE REVIEW

**Review by allenjbaum — APPROVED** [review]
This is a correct fix

**Comment by allenjbaum** [comment]
All changes are expected to update the change log. Once that is done, it will be merged.

**Comment by visitorckw** [comment]
Thank you for the reminder.
I've updated the change log with the required information.

**Comment by allenjbaum** [comment]
We have conflicts because there are multiple changes with the same version number. Could you update the changelog to the latest number+.1?

**Pull request merged**
